apiVersion: v1
kind: Pod
metadata:
 name: cuda8-vector-add-runtime
spec:
 restartPolicy: OnFailure
 containers:
   - name: cuda-vector-add
     image: "docker.io/karve/vector-add-sample:arm64-jetsonnano"
