apiVersion: v1
kind: Pod
metadata:
  name: aravis-box
  namespace: s-pilot
spec:
  hostNetwork: true
  imagePullSecrets:
    - name: s-pilot-registry
    - name: s-pilot-registry-hq
  containers:
    - name: aravis-box
      image: registry.surveily.com/tools.aravis:latest
      imagePullPolicy: IfNotPresent
      securityContext:
        privileged: true
      args:
        - sleep
        - "1000000"
      resources:
        limits:
          memory: 128Mb
          cpu: "1"
