apiVersion: v1
kind: Pod
metadata:
  name: modbus-box
  namespace: s-pilot
spec:
  containers:
    - name: modbus-box
      image: surveily/tools.modbus:1.0-20221012.1
      imagePullPolicy: IfNotPresent
      command:
        - "/bin/sh"
        - "-c"
        - "while sleep 3600; do :; done"
      resources:
        limits:
          memory: 128Mb
          cpu: "1"
