#!/bin/sh

docker build --build-arg version=3.0 -t surveily/developer.dotnet:3.0-sdk -f src/surveily.developer.dotnet.sdk.dockerfile .
docker build --build-arg version=3.1 -t surveily/developer.dotnet:3.1-sdk -f src/surveily.developer.dotnet.sdk.dockerfile .

docker build --build-arg version=3.0 -t surveily/developer.dotnet:3.0-runtime-svc -f src/surveily.developer.dotnet.runtime.svc.dockerfile .
docker build --build-arg version=3.1 -t surveily/developer.dotnet:3.1-runtime-svc -f src/surveily.developer.dotnet.runtime.svc.dockerfile .

docker build --build-arg version=3.0 -t surveily/developer.dotnet:3.0-runtime-web -f src/surveily.developer.dotnet.runtime.web.dockerfile .
docker build --build-arg version=3.1 -t surveily/developer.dotnet:3.1-runtime-web -f src/surveily.developer.dotnet.runtime.web.dockerfile .
