name: Build and Publish Kubeflow Code-server Development Image

on:
  push:
    branches: [master]
    paths:
      - "src/surveily.developer.kubeflow.codeserver/**"

  workflow_dispatch:

env:
  REGISTRY: docker.io
  LOGIN: turowicz
  IMAGE_NAME: surveily/surveily.developer.kubeflow.codeserver

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d')"

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.LOGIN }}
          password: ${{ secrets.REGISTRY_DOCKER }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and Push Kubeflow Code-server Development image
        id: build-and-push
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: src/surveily.developer.kubeflow.codeserver/
          platforms: linux/amd64
          file: src/surveily.developer.kubeflow.codeserver/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ env.IMAGE_NAME }}:pytorch-2.0
            ${{ env.IMAGE_NAME }}:pytorch-2.0-${{ steps.date.outputs.date }}.${{ github.run_number }}
          labels: ${{ steps.meta.outputs.labels }}
